DevCard_MVC/Models/Article.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevCard_MVC.Models
{
    public class Article
    {
        public int Id { get; set; }

        public  string Title { get; set; }
        public  string Description { get; set; }
        public  string Img { get; set; }

        public Article(int id, string title, string description, string img)
        {
            Id = id;
            Title = title;
            Description = description;
            Img = img;
        }
    }
}

DevCard_MVC/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DevCard_MVC.Models
{
    public class Contact
    {
        [Required(ErrorMessage = "لطفا این فیلد را پر کنید")]
        [MaxLength(100 ,ErrorMessage = "حداکثر مجاز کاراکتر 100 میباشد")]
        public string Name { get; set; }

        [EmailAddress]
        [Required(ErrorMessage = "لطفا این فیلد را پر کنید")]
        public string Email { get; set; }
        public string Message { get; set; }
        public string Service { get; set; }
    }
}

DevCard_MVC/Models/ErrorViewModel.cs
using System;

namespace DevCard_MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DevCard_MVC/Models/Project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevCard_MVC.Models
{
    public class Project
    {
        public  int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Client { get; set; }
        public string Img { get; set; }

        public Project(int id, string name, string description, string client, string img)
        {
            Id = id;
            Name = name;
            Description = description;
            Client = client;
            Img = img;
        }
    }
}

DevCard_MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DevCard_MVC.Models;
using Microsoft.AspNetCore.Http;

namespace DevCard_MVC.Controllers
{
    public class HomeController : Controller
    {
       
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Contact()
        {
            var model = new Contact();

            return View(model);
        }

        [HttpPost]
        //public JsonResult Contact(IFormCollection form)
        //{

        //    return Json(Ok());
        //}

        //public JsonResult Contact(IFormCollection form)
        //{
        //    var Name = form["Name"];
        //    return Json(Ok());
        //}
        public IActionResult Contact(Contact form)
        {
            if (ModelState.IsValid == false)
            {
                ViewBag.error= "اطلاعات وارد شده صحیح نیست لطفا دوباره تلاش کنید";
                return View(form);

            }

           ViewBag.success = "فرم شما با موفقیت ارسال شد";
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

DevCard_MVC/ViewComponents/ArticlesViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DevCard_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace DevCard_MVC.ViewComponents
{
    public class ArticlesViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var articles = new List<Article>()
            {
                new Article(1,"Top 3 JavaScript Frameworks", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient..." , "blog-post-thumb-card-1.jpg"),
                new Article(2,"About Remote Working", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient... " , "blog-post-thumb-card-2.jpg"),
                new Article(3,"A Guide to Becoming a Full-Stack Developer", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient... " , "blog-post-thumb-card-3.jpg"),
            };
            return View("_Articles", articles);
        }
    }
}

DevCard_MVC/ViewComponents/ProjectsViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DevCard_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace DevCard_MVC.ViewComponents
{
    public class ProjectsViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var projects = new List<Project>
            {
                new Project(1,"اسنپ فود" , "ارسال سریع و فوری غذا از هر کجای دنیا " , "snap" , "project-1.jpg"),
                new Project(2,"اسنپ" , "ارسال سریع و فوری تاکسی از هر کجای دنیا " , "snap" , "project-2.jpg"),
                new Project(3,"لرنایت" , "یادگیری فوری زبان انگلیسی در منزل با کم ترین قیمت و بهترین کیفیت زیر نظر بهترین و حرفه ای ترین تیم آموزشی  و مشاوره رایگان " , "learnit" , "project-3.jpg"),
                new Project(4,"تهران گردی" , "بشین تو خونت و ببین امروز کجا بری بهتره؟ " , "gardesh" , "project-4.jpg"),

                // بدون کانستراکتور
                //new Project
                //{
                //    Id = 1,
                //    Name = "Project Heading",
                //    Description =
                //        "Project intro lorem ipsum dolor sit amet, consectetuer adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes.",
                //    Client = "Client: Google",
                //    Img = "project-1.jpg"
                //},
                //new Project
                //{
                //    Id = 2,
                //    Name = "Project Heading",
                //    Description =
                //        "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ",
                //    Client = "Client: Dropbox",
                //    Img = "project-2.jpg"
                //},
                //new Project
                //{
                //    Id = 3,
                //    Name = "Project Heading",
                //    Description =
                //        "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.  ",
                //    Client = "Client: Google",
                //    Img = "project-3.jpg"
                //},
                //new Project
                //{
                //    Id = 4,
                //    Name = "Project Heading",
                //    Description =
                //        "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ",
                //    Client = "Client: Uber",
                //    Img = "project-4.jpg"
                //}
            };

            return View("_Projects", projects);
        }
    }
}

DevCard_MVC/Views/Home/Components/Articles/_Articles.cshtml
@model IEnumerable<DevCard_MVC.Models.Article>


<section class="latest-blog-section p-3 p-lg-5">
    <div class="container">
        <h2 class="section-title font-weight-bold mb-5">آخرین مقالات</h2>
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4 mb-5">
                    <div class="card blog-post-card">
                        <img class="card-img-top" src="assets/images/blog/@item.Img" alt="image">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a class="theme-link" href="blog-post.html">
                                    @item.Title
                                </a>
                            </h5>
                            <p class="card-text">
                                @item.Description
                            </p>
                            <p class="mb-0"><a class="more-link" href="blog-post.html">ادامه مطلب</a></p>

                        </div>
                    </div>
                </div>

            }
       

        </div>
    </div>
</section>

DevCard_MVC/Views/Home/Components/Projects/_Projects.cshtml
@model IEnumerable<DevCard_MVC.Models.Project>
<section class="featured-section p-3 p-lg-5">
    <div class="container">
        <h2 class="section-title font-weight-bold mb-5">خاص ترین پروژه ها</h2>
       
        <div class="row">
            @foreach (var item in Model)
            {
            <div class="col-md-6 mb-5">
                <div class="card project-card">
                    <div class="row no-gutters">
                        <div class="col-lg-4 card-img-holder">
                            <img src="~/assets/images/project/@item.Img" class="card-img" alt="image">
                        </div>
                        <div class="col-lg-8">
                            <div class="card-body">
                                <h5 class="card-title">
                                    <a href="project.html" class="theme-link">
                                        @item.Name
                                    </a>
                                </h5>
                                <p class="card-text">
                                    @item.Description
                                </p>
                                <p class="card-text">
                                    <small class="text-muted">@item.Client</small>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            }
        </div>
       
    </div>
</section>

DevCard_MVC/Views/Home/Contact.cshtml
@model Contact
@{
    ViewData["Title"] = "ارتباط با ما";
}
<h2>@ViewData["Title"]</h2>
@*<h3>@ViewData["Message"]</h3>*@

<div class="main-wrapper">
    <section class="cta-section theme-bg-light py-5">
        <div class="container text-center single-col-max-width">
            <h2 class="heading">ارتباط با ما</h2>
            <div class="intro">
                <p>
                    شما می توانید از طریق فرم زیر با ما ارتباط بگیرید. لطفا پس از پرکردن آیتم ها، پیغام مورد نظر را
                    نوشته و ارسال کنید.
                </p>
                <p>از طریق شبکه های اجتماعی با ما در ارتباط باشید</p>
                <ul class="list-inline mb-0">
                    <li class="list-inline-item mb-3">
                        <a class="twitter" href="#">
                            <i class="fab fa-twitter fa-fw fa-lg"></i>
                        </a>
                    </li>

                    <li class="list-inline-item mb-3">
                        <a class="linkedin" href="#">
                            <i class="fab fa-linkedin-in fa-fw fa-lg"></i>
                        </a>
                    </li>
                    <li class="list-inline-item mb-3">
                        <a class="github" href="#">
                            <i class="fab fa-github-alt fa-fw fa-lg"></i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="instagram" href="#">
                            <i class="fab fa-instagram fa-fw fa-lg"></i>
                        </a>
                    </li>
                    <li class="list-inline-item mb-3">
                        <a class="stack-overflow" href="#">
                            <i class="fab fa-stack-overflow fa-fw fa-lg"></i>
                        </a>
                    </li>
                    <li class="list-inline-item mb-3">
                        <a class="medium" href="#">
                            <i class="fab fa-medium-m fa-fw fa-lg"></i>
                        </a>
                    </li>
                    <li class="list-inline-item mb-3">
                        <a class="codepen" href="#">
                            <i class="fab fa-codepen fa-fw fa-lg"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </section>
    <section class="contact-section px-3 py-5 p-md-5">
        <div class="container">
            @if (!string.IsNullOrWhiteSpace(ViewBag.success))
            {
                <div class="alert.success">
                    <p>   @ViewBag.success</p>
                </div>
            }
            
            @if (!string.IsNullOrWhiteSpace(ViewBag.error))
            {
                <div class="alert.danger">
                    <p>   @ViewBag.error</p>
                </div>
            }
            <form id="contact-form" class="contact-form col-lg-8 mx-lg-auto" method="post" asp-action="Contact">
                <h3 class="text-center mb-3">در دسترس باشید!</h3>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label class="sr-only" for="cname">نام</label>
                        <input type="text" class="form-control" asp-for="Name" placeholder="نام"/>
                        <span asp-validation-for="Name"></span>

                    </div>
                    <div class="form-group col-md-6">
                        <label class="sr-only" for="cemail">ایمیل</label>
                        <input type="email" class="form-control" asp-for="Email" placeholder="ایمیل">
                        <span asp-validation-for="Email"></span>
                    </div>
                    <div class="form-group col-12">
                        <select class="custom-select" asp-for="Service">
                            <option selected>سرویس مورد نظر خود را انتخاب کنید...</option>
                            <option value="basic">نقره ای</option>
                            <option value="standard">طلایی</option>
                            <option value="premium">پلاتین</option>
                            <option value="not sure">الماس</option>
                        </select>
                    </div>
                    <div class="form-group col-12">
                        <label class="sr-only" for="cmessage">پیغام شما</label>
                        <textarea class="form-control" asp-for="Message"
                                  placeholder="پیغام خود را وارد نمایید ..." rows="10"></textarea>
                    </div>
                    <div class="form-group col-12">
                        <button type="submit" class="btn btn-block btn-primary py-2">ارسال</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <footer class="footer text-center py-4">
        <small class="copyright">
            تولید شده توسط &copy; <a href="http://www.atriya.com" target="_blank">
                موسسه آموزشی
                آتریا
            </a>
        </small>
    </footer>

</div>

DevCard_MVC/Views/Home/Footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<footer class="footer text-center py-4">
    <small class="copyright">
        تولید شده توسط &copy;
        <a href="http://www.atriya.com" target="_blank">
            موسسه آموزشی
            آتریا
        </a>
    </small>
</footer>

DevCard_MVC/Views/Home/Header.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<header class="header text-center">
    <div class="force-overflow">
        <h1 class="blog-name pt-lg-4 mb-0">
            <a href="@Url.Action("Index" , "Home")">حسین عباس آبادی</a>
        </h1>

        <nav class="navbar navbar-expand-lg navbar-dark">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                    aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navigation" class="collapse navbar-collapse flex-column">
                <div class="profile-section pt-3 pt-lg-0">
                    <img class="profile-image mb-3 rounded-circle mx-auto" src="~/assets/images/me.jpeg" alt="image">

                    <div class="bio mb-3">
                        سلام، حسین عباس آبادی هستم از موسسه آموزشی آتریا. به وبسایت شخصی من خوش
                        آمدید.
                    </div>
                    <ul class="social-list list-inline py-2 mx-auto">
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fab fa-twitter fa-fw"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fab fa-linkedin-in fa-fw"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fab fa-github-alt fa-fw"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fab fa-stack-overflow fa-fw"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fab fa-codepen fa-fw"></i>
                            </a>
                        </li>
                    </ul>
                    <hr>
                </div>
                <ul class="navbar-nav flex-column text-right">
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Home">
                            <i class="fas fa-user fa-fw ml-2"></i>صفحه اصلی<span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Contact" , "Home")">
                            <i class="fas fa-envelope-open-text fa-fw ml-2"></i>ارتباط با ما
                        </a>
                    </li>
                </ul>
            </div>

        </nav>
    </div>
</header>

DevCard_MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "صفحه اصلی";
}


<div class="main-wrapper">
    <section class="about-me-section p-3 p-lg-5 theme-bg-light">
        <div class="container">
            <div class="profile-teaser media flex-column flex-lg-row">
                <img class="profile-image mb-3 mb-lg-0 ml-lg-5 mr-md-0" src="assets/images/me.jpeg" alt="">
                <div class="media-body">
                    <h2 class="name font-weight-bold mb-1">حسین عباس آبادی</h2>
                    <div class="tagline mb-3">برنامه نویس ارشد</div>
                    <div class="bio mb-4">
                        لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از
                        طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و
                        جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.
                    </div>
                    <div class="mb-4">
                        <a class="btn btn-primary mr-2 mb-3" href="http://www.atriya.com">
                            <i class="fas fa-arrow-alt-circle-right ml-2"></i><span class="d-none d-md-inline">
                                برو
                                به
                            </span> آتریا
                        </a>
                        <a class="btn btn-secondary mb-3" href="#">
                            <i class="fas fa-file-alt ml-2"></i>
                            <span class="d-none d-md-inline">مشاهده </span> نمونه کارها
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </section>
   
    @*@await Html.PartialAsync("Projects")*@

    @await Component.InvokeAsync("Projects")
    <div class="container">
        <hr>
    </div>

    @await Component.InvokeAsync("Articles")





</div>

DevCard_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - DevCard_MVC</title>
    <script defer src="~/assets/fontawesome/js/all.js"></script>
    <link rel="stylesheet" href="~/assets/css/theme-1.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
</head>
<body>

    <partial name="Header" />

<div class="main-wrapper">
    @RenderBody()

    <partial name="Footer"/>


</div>


<script src="~/assets/plugins/jquery-3.4.1.min.js"></script>
<script src="~/assets/plugins/popper.min.js"></script>
<script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
@RenderSection("Scripts", required: false)
</body>
</html>